apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: demos
  labels:
    usage: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azurefile-secret
    secretNamespace: demos
    shareName: nfs
    readOnly: false
