apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: san-pvc
  namespace: demos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: acstor-managed
  resources:
    requests:
      storage: 100Gi
