apiVersion: containerstorage.azure.com/v1alpha1
kind: StoragePool
metadata:
  name: san-storagepool
  namespace: acstor
spec:
  poolType:
    elasticSan: {}
  resources:
    requests: { "storage": 1Ti }
