apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premiumdisk-pvc
  namespace: demos
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
