apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ultradisk-pvc
  namespace: demos
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ultra-disk-sc
  resources:
    requests:
      # See azure-ultra-disk-sc.yaml for detailed configuration
      storage: 256Gi