apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ultradisk
  namespace: demos
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ultra-disk-sc
  resources:
    requests:
      storage: 1000Gi