apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-pv
  namespace: demos
  labels:
    usage: smb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azurefile-secret
    secretNamespace: demos
    shareName: smb
    readOnly: false
