apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc
  namespace: demos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 100Gi
