apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netapp-nfs-pvc
  namespace: demos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: netapp-nfs-pv
