apiVersion: v1
kind: PersistentVolume
metadata:
  name: netapp-nfs-pv
  namespace: demos
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4.1
    - noatime
    - rw
    - hard
    - rsize=1048576
    - wsize=1048576
    - sec=sys
    - tcp
  nfs:
    server: 10.4.0.4
    path: /netappnfs
