apiVersion: v1
kind: PersistentVolume
metadata:
  name: blobfuse-pv
  namespace: demos
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: blobfusepv
    volumeAttributes:
      storageAccount: myaksstorage00010
      containerName: blob
    nodeStageSecretRef:
      name: azurefile-secret
      namespace: demos
