apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobfuse-pvc
  namespace: demos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: blob-csi-fuse
  resources:
    requests:
      storage: 100Gi
  volumeName: blobfuse-pv
