apiVersion: v1
kind: PersistentVolume
metadata:
  name: blobfuse-pv
  namespace: demos
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: blob-csi-fuse
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: blobfusepv
    volumeAttributes:
      resourceGroup: ${resourceGroupName}
      storageAccount: ${premiumStorageName}
      containerName: ${premiumStorageBlobContainerName}
    nodeStageSecretRef:
      name: azureblob-secret
      namespace: demos
