apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: demos
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # From:
  # https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/pv-azurefile-csi.yaml
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: nfspv
    volumeAttributes:
      storageAccount: myaksstorage00010
      shareName: nfs
      protocol: nfs
    nodeStageSecretRef:
      name: azurefile-secret
      namespace: demos
