apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-fs-tester-demo
  namespace: demos
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp-fs-tester-demo
  template:
    metadata:
      labels:
        app: webapp-fs-tester-demo
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        # - image: jannemattila/webapp-update:1.0.9
        - image: jannemattila/webapp-fs-tester:1.1.13
          imagePullPolicy: Always
          name: webapp-fs-tester-demo
          # https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/fail-to-mount-azure-disk-volume#cause-changing-ownership-and-permissions-for-large-volume-takes-much-time
          # securityContext:
          #   runAsUser: 1000
          #   runAsGroup: 3000
          #   fsGroup: 2000
          #   fsGroupChangePolicy: "OnRootMismatch"
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 150m
          #     memory: 150Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            # - name: empty
            #   mountPath: /mnt/empty
            # - name: hostpath
            #   mountPath: /mnt/hostpath
            # - name: nfs
            #   mountPath: /mnt/nfs
            - name: smb
              mountPath: /mnt/smb
            # - name: blobfuse
            #   mountPath: /mnt/blobfuse
            # - name: premiumdisk
            #   mountPath: /mnt/premiumdisk
            # - name: premiumdisk-v2
            #   mountPath: /mnt/premiumdisk-v2
            # - name: ultradisk
            #   mountPath: /mnt/ultradisk
            # - name: netapp-nfs
            #   mountPath: /mnt/netapp-nfs
      volumes:
        # - name: empty
        #   emptyDir: {}
        # - name: hostpath
        #   hostPath:
        #     path: /mnt
        # - name: nfs
        #   persistentVolumeClaim:
        #     claimName: nfs-pvc
        - name: smb
          persistentVolumeClaim:
            claimName: smb-pvc
        # - name: blobfuse
        #   persistentVolumeClaim:
        #     claimName: blobfuse-pvc
        # - name: premiumdisk
        #   persistentVolumeClaim:
        #     claimName: premiumdisk-pvc
        # - name: premiumdisk
        #   persistentVolumeClaim:
        #     claimName: premiumdisk-pvc
        # - name: premiumdisk-v2
        #   persistentVolumeClaim:
        #     claimName: premiumdisk-v2-pvc
        # - name: ultradisk
        #   persistentVolumeClaim:
        #     claimName: ultradisk-pvc
        # - name: netapp-nfs
        #   persistentVolumeClaim:
        #     claimName: netapp-nfs-pvc
